package com.noop.ui

import java.io.File
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Assume.assumeTrue
import org.junit.Test

/** Source contracts for the production Compose Daily Action presentation. */
class DailyActionTodayContractTest {
    private fun find(relative: String): File? {
        val root = File(System.getProperty("user.dir") ?: ".")
        return listOf(
            File(root, relative),
            File(root, "app/$relative"),
            File(root, "android/app/$relative"),
        ).firstOrNull(File::isFile)
    }

    private fun source(relative: String): String? = find(relative)?.readText()

    @Test
    fun todayUsesEvidenceGatedPlannerForAllFiveStates() {
        val text = source("src/main/java/com/noop/ui/TodayScreen.kt")
        assumeTrue("TodayScreen.kt unavailable", text != null)
        val today = text!!

        assertTrue(today.contains("import com.noop.analytics.DailyActionPlanner"))
        assertTrue(today.contains("NoopPrefs.dailyActionCheckIn(context, selectedDayKey)"))
        assertTrue(today.contains("NoopPrefs.setDailyActionCheckIn("))
        assertTrue(today.contains("viewModel.onAdaptiveDayInputsChanged()"))
        assertTrue(today.contains("DailyActionPlanner.plan("))
        assertTrue(today.contains("TodaySection.WHY -> TodayDetailSection("))
        assertTrue(today.contains("DailyPlanWhySection("))
        assertTrue(today.contains("TodaySection.TARGET -> TodayDetailSection("))
        assertTrue(today.contains("DailyPlanTargetSection("))
        assertTrue(today.contains("TodaySection.WATCH -> TodayDetailSection("))
        assertTrue(today.contains("DailyPlanWatchSection("))
        assertTrue(
            today.contains(
                "it.flag == ReadinessEngine.Flag.WATCH || it.flag == ReadinessEngine.Flag.BAD"
            )
        )
        listOf("CHECK_IN_NEEDED", "CALIBRATING", "RECOVERY_SHIFT", "STOP", "READY").forEach {
            assertTrue("Missing $it presentation", today.contains("Availability.$it"))
        }
        assertTrue(today.contains("R.string.daily_plan_effort_scale"))
        assertFalse(today.contains("Your body can take a demanding session"))
        assertFalse(today.contains("A solid session is well supported"))
    }

    @Test
    fun checkInAndSleepTargetChangesReevaluateAdaptiveGuidance() {
        val today = source("src/main/java/com/noop/ui/TodayScreen.kt")
        val viewModel = source("src/main/java/com/noop/ui/AppViewModel.kt")
        assumeTrue("Adaptive-day sources unavailable", today != null && viewModel != null)

        assertTrue(today!!.contains("viewModel.onAdaptiveDayInputsChanged()"))
        assertTrue(viewModel!!.contains("fun onAdaptiveDayInputsChanged()"))
        assertTrue(viewModel.contains("adaptiveDayInputEvaluationJob?.cancel()"))
        assertTrue(viewModel.contains("val wasExplicit = windDownStore.hasExplicitSleepNeed"))
        assertTrue(
            viewModel.contains(
                "if (!wasExplicit || windDownStore.sleepNeedMinutes != prior)"
            )
        )
        assertTrue(viewModel.contains("onAdaptiveDayInputsChanged()"))
    }

    @Test
    fun generatedResourcesHaveIdenticalKeysAcrossNineLocales() {
        val folders = listOf(
            "values", "values-de", "values-es", "values-fr", "values-it",
            "values-pt-rPT", "values-ru", "values-zh", "values-zh-rTW",
        )
        val resources = folders.mapNotNull { folder ->
            source("src/main/res/$folder/daily_plan.xml")?.let { folder to it }
        }
        assumeTrue("Daily-plan resources unavailable", resources.size == folders.size)

        val keyPattern = Regex("""name="(daily_plan_[^"]+)"""")
        val expected = keyPattern.findAll(resources.first().second)
            .map { it.groupValues[1] }
            .toSet()
        assertTrue(expected.size >= 25)
        resources.forEach { (folder, text) ->
            assertEquals(folder, expected, keyPattern.findAll(text).map { it.groupValues[1] }.toSet())
            assertTrue(text.contains("Generated by Tools/DailyPlanLocalization/generate.rb"))
        }
    }
}
