#!/usr/bin/env ruby
# frozen_string_literal: true

require "cgi"
require "json"
require "fileutils"

tool_dir = File.expand_path(__dir__)
repo_root = File.expand_path("../..", tool_dir)
source_path = File.join(tool_dir, "safety_strings.json")
source = JSON.parse(File.read(source_path))

locales = {
  "en" => "values",
  "de" => "values-de",
  "es" => "values-es",
  "fr" => "values-fr",
  "it" => "values-it",
  "pt-PT" => "values-pt-rPT",
  "ru" => "values-ru",
  "zh-Hans" => "values-zh",
  "zh-Hant" => "values-zh-rTW"
}.freeze

required_locales = locales.keys.sort
source.each do |key, translations|
  missing = required_locales - translations.keys
  unknown = translations.keys - locales.keys
  abort("#{key}: missing required locales #{missing.inspect}") unless missing.empty?
  abort("#{key}: unknown locales #{unknown.inspect}") unless unknown.empty?
end

def android_key(key)
  key.tr(".", "_")
end

def android_xml(value)
  CGI.escapeHTML(value)
    .gsub("&#39;", "'")
end

def apple_format(value)
  value
    .gsub(/%(\d+)\$s/, '%\1$@')
    .gsub(/%(\d+)\$d/, '%\1$lld')
end

locales.each do |locale, directory|
  path = File.join(repo_root, "android/app/src/main/res", directory, "safety.xml")
  FileUtils.mkdir_p(File.dirname(path))
  lines = source.sort.map do |key, translations|
    value = translations[locale]
    next unless value

    %(    <string name="#{android_key(key)}">#{android_xml(value)}</string>)
  end.compact
  File.write(
    path,
    [
      %(<?xml version="1.0" encoding="utf-8"?>),
      "<resources>",
      "    <!-- Generated by Tools/SafetyLocalization/generate.rb. -->",
      *lines,
      "</resources>",
      ""
    ].join("\n")
  )
end

catalog_path = File.join(repo_root, "Strand/Resources/Localizable.xcstrings")
catalog = File.read(catalog_path)
safety_key = /^\s+"(?:managed\.)?safety\.[^"]+":/
catalog = catalog.lines.reject { |line| line.match?(safety_key) }.join
marker = "\n  },\n  \"version\":"
head, tail = catalog.split(marker, 2)
abort("Could not find String Catalog closing marker") unless head && tail

head = head.rstrip.sub(/,\z/, "")
entries = source.sort.map do |key, translations|
  localizations = translations.to_h do |locale, value|
    [
      locale,
      {
        "stringUnit" => {
          "state" => "translated",
          "value" => apple_format(value)
        }
      }
    ]
  end
  %(    #{JSON.generate(key)}: #{JSON.generate({ "localizations" => localizations })})
end

generated_catalog = "#{head},\n#{entries.join(",\n")}#{marker}#{tail}"
generated_counts = generated_catalog.lines
  .map do |line|
    next unless line.match?(safety_key)

    line.match(/^\s+"([^"]+)":/)&.captures&.first
  end
  .compact
  .each_with_object(Hash.new(0)) { |key, counts| counts[key] += 1 }
invalid_keys = source.keys.select { |key| generated_counts[key] != 1 }
abort("Generated Safety catalog contains missing or duplicate keys: #{invalid_keys.inspect}") unless invalid_keys.empty?

File.write(catalog_path, generated_catalog)

puts "Generated #{source.length} Safety strings for #{locales.length} locales."
