#!/usr/bin/env ruby
# frozen_string_literal: true

require "cgi"
require "json"
require "fileutils"

tool_dir = File.expand_path(__dir__)
repo_root = File.expand_path("../..", tool_dir)
source_path = File.join(tool_dir, "daily_plan_strings.json")
source = JSON.parse(File.read(source_path))

locales = {
  "en" => "values",
  "de" => "values-de",
  "es" => "values-es",
  "fr" => "values-fr",
  "it" => "values-it",
  "pt-PT" => "values-pt-rPT",
  "ru" => "values-ru",
  "zh-Hans" => "values-zh",
  "zh-Hant" => "values-zh-rTW"
}.freeze

expected_locales = locales.keys.sort
source.each do |key, translations|
  actual = translations.keys.sort
  abort("#{key}: expected #{expected_locales.inspect}, got #{actual.inspect}") unless actual == expected_locales
end

def android_key(key)
  key.tr(".", "_")
end

def android_xml(value)
  CGI.escapeHTML(value).gsub("&#39;", "\\\\'")
end

locales.each do |locale, directory|
  path = File.join(repo_root, "android/app/src/main/res", directory, "daily_plan.xml")
  FileUtils.mkdir_p(File.dirname(path))
  lines = source.sort.map do |key, translations|
    %(    <string name="#{android_key(key)}">#{android_xml(translations.fetch(locale))}</string>)
  end
  File.write(
    path,
    [
      %(<?xml version="1.0" encoding="utf-8"?>),
      "<resources>",
      "    <!-- Generated by Tools/DailyPlanLocalization/generate.rb. -->",
      *lines,
      "</resources>",
      ""
    ].join("\n")
  )
end

catalog_path = File.join(repo_root, "Strand/Resources/Localizable.xcstrings")
catalog = File.read(catalog_path)
catalog = catalog.lines.reject { |line| line.match?(/^\s+"daily_plan\.[^"]+":/) }.join
marker = "\n  },\n  \"version\":"
head, tail = catalog.split(marker, 2)
abort("Could not find String Catalog closing marker") unless head && tail

head = head.rstrip.sub(/,\z/, "")
entries = source.sort.map do |key, translations|
  localizations = translations.to_h do |locale, value|
    [
      locale,
      {
        "stringUnit" => {
          "state" => "translated",
          "value" => value
        }
      }
    ]
  end
  %(    #{JSON.generate(key)}: #{JSON.generate({ "localizations" => localizations })})
end

File.write(
  catalog_path,
  "#{head},\n#{entries.join(",\n")}#{marker}#{tail}"
)

puts "Generated #{source.length} Daily Plan strings for #{locales.length} locales."
