import Foundation

enum FeedbackScreenshotFixture {
    static let rawMetadataBearing = Data(
        base64Encoded:
            "iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAAAXNSR0IArs4c6QAAACxlWElmTk9PUCBzeW50aGV0aWMgbWV0YWRhdGEgdGhhdCBtdXN0IGJlIHJlbW92ZWQJg4JOAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAHGlET1QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQhYJ0AAAABFJREFUeJxjUEhY8B+EGWAMAEa0CH0mQ0nfAAAAAElFTkSuQmCC"
    )!

    static let sanitized = Data(
        base64Encoded:
            "iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAAAXNSR0IArs4c6QAAAAlwSFlzAAALEwAACxMBAJqcGAAAABFJREFUeJxjUEhY8B+EGWAMAEa0CH0mQ0nfAAAAAElFTkSuQmCC"
    )!
}
