#!/usr/bin/env python3
"""Refresh the hash-locked Python runtime from reviewed license components.

Run this only as part of an intentional dependency update.  The release gate
does not contact PyPI; it verifies the checked-in lock and license inventory.
"""

from __future__ import annotations

import argparse
import json
import re
import urllib.parse
import urllib.request
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LICENSE_DIR = ROOT / "ThirdPartyNotices" / "licenses" / "python"
REQUIREMENT_EXTRAS = {
    "pyjwt": "crypto",
    "uvicorn": "standard",
}


def components() -> list[tuple[str, str]]:
    result = []
    for path in sorted(LICENSE_DIR.glob("*.txt")):
        match = re.fullmatch(r"(.+)-([0-9][0-9A-Za-z.+!]*)\.txt", path.name)
        if not match:
            raise SystemExit(f"unrecognized Python license filename: {path}")
        result.append((match.group(1), match.group(2)))
    if not result:
        raise SystemExit(f"no reviewed Python licenses found under {LICENSE_DIR}")
    return result


def render() -> str:
    lines = [
        "# Fully resolved NOOP server runtime for CPython 3.12 / Linux.",
        "# Generated by Tools/refresh-server-runtime-lock.py after license review.",
        "# Install only with: python -m pip install --require-hashes -r requirements.lock",
    ]
    for name, version in components():
        quoted_name = urllib.parse.quote(name, safe="")
        quoted_version = urllib.parse.quote(version, safe="")
        url = f"https://pypi.org/pypi/{quoted_name}/{quoted_version}/json"
        with urllib.request.urlopen(url, timeout=30) as response:
            payload = json.load(response)
        hashes = sorted(
            {
                entry["digests"]["sha256"]
                for entry in payload.get("urls", [])
                if not entry.get("yanked") and entry.get("digests", {}).get("sha256")
            }
        )
        if not hashes:
            raise SystemExit(
                f"PyPI returned no non-yanked hashes for {name}=={version}"
            )
        extra = REQUIREMENT_EXTRAS.get(name)
        requirement_name = f"{name}[{extra}]" if extra else name
        lines.append(f"{requirement_name}=={version} \\")
        for index, digest in enumerate(hashes):
            continuation = " \\" if index < len(hashes) - 1 else ""
            lines.append(f"    --hash=sha256:{digest}{continuation}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "server" / "requirements.lock",
    )
    args = parser.parse_args()
    content = render()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    print(f"Wrote {len(components())} hash-locked runtime packages to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
